# version: '3.8'
# MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
    - "6379:6379"     
    volumes:
      - redis-data:/data # lưu file .rdb/.aof ra host để không mất dữ liệu khi container bị xoá
    command: ["redis-server", "--appendonly", "yes"] # bật AOF để lưu dữ liệu bền hơn

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8000
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/iahsea?authSource=admin
      # - DB_HOST=host.docker.internal
      - REDIS_HOST=redis            # Host Redis, trỏ theo service name trong compose
      - REDIS_PORT=6379
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db-mongo
      - redis      

  redisinsight:
    image: redis/redisinsight:latest
    container_name: my-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  mongodb:
  redis-data:     
  
  # docker compose -p iahsea-nest up -d